import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const weatherStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0E1A',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
  },
  floatingCard: {
    position: 'absolute',
    top: 20,
    left: 15,
    right: 15,
    backgroundColor: 'rgba(15, 25, 45, 0.92)',
    borderRadius: 20,
    padding: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 170, 0.3)',
    shadowColor: '#00D4AA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
    maxHeight: '35%', // Limit height to 35% of screen
    zIndex: 1000,
  },
  weatherTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#00F5FF',
    marginBottom: 3,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 245, 255, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  coordinates: {
    fontSize: 11,
    color: '#00D4AA',
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: '500',
  },
  temperature: {
    fontSize: 36,
    fontWeight: '200',
    color: '#FF6B6B',
    textAlign: 'center',
    marginBottom: 5,
    textShadowColor: 'rgba(255, 107, 107, 0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  condition: {
    fontSize: 14,
    color: '#FFE66D',
    textAlign: 'center',
    marginBottom: 12,
    textTransform: 'capitalize',
    fontWeight: '600',
  },
  weatherDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  detailItem: {
    width: '48%',
    marginBottom: 6,
    backgroundColor: 'rgba(0, 212, 170, 0.08)',
    borderRadius: 8,
    padding: 6,
    borderLeftWidth: 2,
    borderLeftColor: '#00D4AA',
  },
  detailLabel: {
    fontSize: 10,
    color: '#00D4AA',
    marginBottom: 2,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  detailValue: {
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '700',
  },
  loadingText: {
    color: '#00F5FF',
    textAlign: 'center',
    fontSize: 16,
    marginTop: 20,
    fontWeight: '500',
  },
  errorText: {
    color: '#FF6B6B',
    textAlign: 'center',
    fontSize: 14,
    marginTop: 10,
    fontWeight: '500',
  },
  lastUpdated: {
    fontSize: 12,
    color: '#A0A0A0',
    textAlign: 'center',
    marginTop: 15,
    fontStyle: 'italic',
  },
  satelliteInfo: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 212, 170, 0.3)',
  },
  satelliteTag: {
    backgroundColor: 'rgba(0, 212, 170, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#00D4AA',
  },
  satelliteText: {
    color: '#00F5FF',
    fontSize: 11,
    fontWeight: '700',
  },
});

export const searchStyles = StyleSheet.create({
  searchContainer: {
    position: 'absolute',
    bottom: 20,
    left: 15,
    right: 15,
    backgroundColor: 'rgba(15, 25, 45, 0.95)',
    borderRadius: 15,
    padding: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 170, 0.4)',
    shadowColor: '#00D4AA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    maxHeight: '50%', // Limit height
  },
  searchTitle: {
    color: '#00F5FF',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 18,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 245, 255, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  locationGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  locationButton: {
    width: '48%',
    backgroundColor: 'rgba(0, 212, 170, 0.15)',
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 170, 0.3)',
    shadowColor: '#00D4AA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  locationButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  currentLocationButton: {
    backgroundColor: 'rgba(255, 107, 107, 0.2)',
    borderColor: 'rgba(255, 107, 107, 0.4)',
  },
  closeButton: {
    position: 'absolute',
    top: 15,
    right: 20,
    padding: 5,
    backgroundColor: 'rgba(255, 107, 107, 0.2)',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#FF6B6B',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export const fabStyles = StyleSheet.create({
  fab: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#00D4AA',
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#00D4AA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderWidth: 2,
    borderColor: 'rgba(0, 245, 255, 0.3)',
  },
  fabIcon: {
    fontSize: 22,
    color: '#ffffff',
  },
});

export const loadingStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0A0E1A',
  },
  text: {
    color: '#00F5FF',
    fontSize: 18,
    marginTop: 20,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 245, 255, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  logo: {
    fontSize: 36,
    color: '#00D4AA',
    fontWeight: 'bold',
    marginBottom: 20,
    textShadowColor: 'rgba(0, 212, 170, 0.4)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
  },
});